//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_sys_FieldNameDefs
    {
        public int isid { get; set; }
        public string AppCode { get; set; }
        public string MACAddress { get; set; }
        public string IPAddress { get; set; }
        public string UserCode { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string DisplayName { get; set; }
        public string Remark { get; set; }
        public string FlagDisplay { get; set; }
    }
}
