//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_sys_Log
    {
        public int isid { get; set; }
        public string GUID32 { get; set; }
        public string LogUser { get; set; }
        public System.DateTime LogDate { get; set; }
        public int OPType { get; set; }
        public string TableName { get; set; }
        public string KeyFieldName { get; set; }
        public string DocNo { get; set; }
        public string IsMaster { get; set; }
    }
}
