//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WCS_HS
    {
        public int HS_Id { get; set; }
        public string HS_Name { get; set; }
        public string HS_Info { get; set; }
        public Nullable<int> HS_Code { get; set; }
        public Nullable<int> HS_IsDispay { get; set; }
    }
}
