//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WCS_RoadWay
    {
        public int RoadWay_Id { get; set; }
        public string RoadWay_Name { get; set; }
        public Nullable<int> RoadWay_IsUse { get; set; }
        public Nullable<int> RoadWay_SCNo { get; set; }
        public Nullable<int> RoadWay_SCState { get; set; }
        public Nullable<System.DateTime> RoadWay_UpdateTime { get; set; }
    }
}
