//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WCS_Station
    {
        public int Station_Id { get; set; }
        public string Station_Name { get; set; }
        public string Station_InType { get; set; }
        public string Station_OutType { get; set; }
        public Nullable<int> LinkRoadWayID { get; set; }
        public string Remark { get; set; }
    }
}
