//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WCS_Address
    {
        public int IsID { get; set; }
        public string ConnectName { get; set; }
        public string ConnectIP { get; set; }
        public string ConnectId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string DBAddress { get; set; }
        public Nullable<int> ReadLength { get; set; }
        public string ReadValue { get; set; }
        public string WriteValue { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> WriteFlag { get; set; }
        public Nullable<System.DateTime> WriteDate { get; set; }
        public string Remark { get; set; }
    }
}
