//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_StockDtl
    {
        public int IsId { get; set; }
        public string Stock_PositionId { get; set; }
        public string Stock_PalletId { get; set; }
        public string StockDtl_BillNo { get; set; }
        public Nullable<int> StockDtl_Item { get; set; }
        public string StockDtl_LinkNo { get; set; }
        public Nullable<int> StockDtl_LinkItem { get; set; }
        public Nullable<int> StockDtl_Type { get; set; }
        public Nullable<int> StockDtl_Status { get; set; }
        public string StockDtl_MaterialCode { get; set; }
        public string StockDtl_MaterialName { get; set; }
        public Nullable<decimal> StockDtl_MaterialQty { get; set; }
        public string StockDtl_MaterialBarcode { get; set; }
        public string StockDtl_MaterialUnit { get; set; }
        public string StockDtl_IsLock { get; set; }
        public string StockDtl_IsCheck { get; set; }
        public string StockDtl_Batch { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> UpdateBy { get; set; }
    }
}
