//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Stock
    {
        public string Stock_PositionId { get; set; }
        public string Stock_PalletId { get; set; }
        public int Stock_StockStatus { get; set; }
        public string Stock_StockType { get; set; }
        public System.DateTime Stock_UpdateTime { get; set; }
        public int Stock_CheckStatus { get; set; }
        public System.DateTime Stock_CheckTime { get; set; }
    }
}
