//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_WareCell
    {
        public string WareCell_Name { get; set; }
        public string WareCell_Warehouse { get; set; }
        public string WareCell_Zone { get; set; }
        public string WareCell_State { get; set; }
        public string WareCell_Spec { get; set; }
        public Nullable<decimal> WareCell_MaxWeight { get; set; }
        public Nullable<int> WareCell_Row { get; set; }
        public Nullable<int> WareCell_Column { get; set; }
        public Nullable<int> WareCell_Layer { get; set; }
        public string WareCell_IsStop { get; set; }
        public string WareCell_PalletId { get; set; }
    }
}
