//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_TaskLog
    {
        public string IsId { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public Nullable<int> Task_WorkStatusOld { get; set; }
        public Nullable<int> Task_WorkStatusNew { get; set; }
        public string Task_ClientIp { get; set; }
        public string Task_ClientName { get; set; }
        public string Task_LoginUser { get; set; }
        public Nullable<System.DateTime> Task_LastTime { get; set; }
    }
}
