//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Department
    {
        public string Department_ID { get; set; }
        public string Department_Name { get; set; }
        public string Department_Attribute { get; set; }
        public string Department_IsStop { get; set; }
        public string Department_Creator { get; set; }
        public Nullable<System.DateTime> Department_CreateTime { get; set; }
        public string Department_Editor { get; set; }
        public Nullable<System.DateTime> Department_EditTime { get; set; }
    }
}
