//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_BusinessTables
    {
        public int isid { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> SortID { get; set; }
        public string FormName { get; set; }
        public string FormNameSpace { get; set; }
        public string FormCaption { get; set; }
        public string KeyFieldName { get; set; }
        public string Table1 { get; set; }
        public string Table1Name { get; set; }
        public string Table2 { get; set; }
        public string Table2Name { get; set; }
        public string Table3 { get; set; }
        public string Table3Name { get; set; }
        public string Table4 { get; set; }
        public string Table4Name { get; set; }
        public string Table5 { get; set; }
        public string Table5Name { get; set; }
    }
}
