//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AttachFile
    {
        public int FileID { get; set; }
        public string DocID { get; set; }
        public string FileTitle { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<decimal> FileSize { get; set; }
        public byte[] FileBody { get; set; }
        public string IsDroped { get; set; }
    }
}
