//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Customer
    {
        public int ISID { get; set; }
        public string CustomerCode { get; set; }
        public string NativeName { get; set; }
        public string EnglishName { get; set; }
        public string AttributeCodes { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string CountryCode { get; set; }
        public string CityCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string PostalCode { get; set; }
        public string ZipCode { get; set; }
        public string WebAddress { get; set; }
        public string Email { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
        public string BankAddress { get; set; }
        public string ContactPerson { get; set; }
        public string Remark { get; set; }
        public string InUse { get; set; }
        public Nullable<int> PaymentTerm { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
