//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public int isid { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CategoryId { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string Supplier { get; set; }
        public string Remark { get; set; }
    }
}
