//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCS_Info_SC
    {
        public int IsID { get; set; }
        public string SCNo { get; set; }
        public string SCWorkModel { get; set; }
        public string SCType { get; set; }
        public string SCWorkStatus { get; set; }
        public string SCCurrentStation { get; set; }
        public string SC1Task { get; set; }
        public string SC1WorkType { get; set; }
        public string SC1FromPosition { get; set; }
        public string SC1ToPosition { get; set; }
        public string SC1Error { get; set; }
        public string SetTime { get; set; }
        public string SC2Task { get; set; }
        public string SC2WorkType { get; set; }
        public string SC2FromPositon { get; set; }
        public string SC2ToPosition { get; set; }
        public string SC2Error { get; set; }
        public string SCConnect { get; set; }
        public string IsActivation { get; set; }
    }
}
