//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCS_Info_Port
    {
        public int IsId { get; set; }
        public Nullable<int> Port_Id { get; set; }
        public string Port_Name { get; set; }
        public string Port_InType { get; set; }
        public string Port_OutType { get; set; }
        public string Port_SortType { get; set; }
        public string Port_AccountType { get; set; }
        public string Port_CheckType { get; set; }
        public string Port_SeeType { get; set; }
        public Nullable<int> Port_IsStop { get; set; }
        public string Remark { get; set; }
    }
}
