//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_BillMoveDtl
    {
        public int IsId { get; set; }
        public string Bill_BillNo { get; set; }
        public int BillDtl_NItem { get; set; }
        public string BillDtl_LinkNo { get; set; }
        public Nullable<int> BillDtl_LinkItem { get; set; }
        public string BillDtl_MaterialCode { get; set; }
        public string BillDtl_MaterialName { get; set; }
        public string BillDtl_MaterialBarcode { get; set; }
        public string BillDtl_MaterialUnit { get; set; }
        public Nullable<int> BillDtl_MaterialQty { get; set; }
        public Nullable<int> BillDtl_WorkStatus { get; set; }
        public Nullable<int> BillDtl_OptionQty { get; set; }
        public Nullable<int> BillDtl_FinishQty { get; set; }
        public Nullable<int> BillDtl_CheckStatus { get; set; }
        public Nullable<int> BillDtl_CheckQty { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
