//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Task
    {
        public int Task_Id { get; set; }
        public string Task_InteractNum { get; set; }
        public Nullable<int> Task_OpcNo { get; set; }
        public string Task_BillNo { get; set; }
        public string Task_PalletId { get; set; }
        public string Task_TaskType { get; set; }
        public Nullable<int> Task_OptionStation { get; set; }
        public Nullable<int> Task_PortNum { get; set; }
        public Nullable<int> Task_TaskStatus { get; set; }
        public string Task_FromWareCell { get; set; }
        public string Task_ToWareCell { get; set; }
        public Nullable<int> Task_PriorityFirst { get; set; }
        public Nullable<int> Task_PrioritySecond { get; set; }
        public string Task_Remark { get; set; }
        public Nullable<System.DateTime> Task_CreatorDate { get; set; }
        public string Task_CreatedBy { get; set; }
        public Nullable<System.DateTime> Task_StartDate { get; set; }
        public string Task_StartBy { get; set; }
        public Nullable<System.DateTime> Task_FinishDate { get; set; }
        public string Task_FinishBy { get; set; }
        public string Task_AccountType { get; set; }
    }
}
