//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Pallet
    {
        public string Pallet_No { get; set; }
        public Nullable<int> Pallet_PrintQty { get; set; }
        public Nullable<int> Pallet_UseQty { get; set; }
        public string Pallet_Notes { get; set; }
        public string Pallet_Status { get; set; }
        public string Pallet_Spec { get; set; }
        public string Pallet_IsUse { get; set; }
    }
}
