//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Customer
    {
        public string Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Attribute { get; set; }
        public string Customer_Address1 { get; set; }
        public string Customer_Address2 { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Tel { get; set; }
        public string Customer_ContactMan { get; set; }
        public string Customer_CarNo { get; set; }
        public string Custormer_City { get; set; }
        public string Customer_Fax { get; set; }
        public string Customer_WebAddress { get; set; }
        public Nullable<bool> Customer_IsStop { get; set; }
        public string Customer_Remark { get; set; }
    }
}
