//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Warehouse
    {
        public int IsId { get; set; }
        public string Warehouse_Id { get; set; }
        public string Warehouse_Name { get; set; }
        public string Warehouse_Location { get; set; }
        public string Warehouse_Notes { get; set; }
        public string Warehouse_IsUse { get; set; }
        public string Warehouse_EditWho { get; set; }
        public Nullable<System.DateTime> Warehouse_EditTime { get; set; }
        public string Warehouse_Creator { get; set; }
        public Nullable<System.DateTime> Warehouse_CreateTime { get; set; }
    }
}
