//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Material
    {
        public string Material_Code { get; set; }
        public string Material_barcode { get; set; }
        public string Material_Name { get; set; }
        public string Material_Type { get; set; }
        public string Material_Attribute { get; set; }
        public string Material_IsStop { get; set; }
        public string Material_Unit { get; set; }
        public string Material_Creator { get; set; }
        public Nullable<System.DateTime> Material_CreateTime { get; set; }
        public string Material_Editor { get; set; }
        public Nullable<System.DateTime> Material_EditTime { get; set; }
        public Nullable<double> Material_ActPrice { get; set; }
        public Nullable<double> Material_PrePrice { get; set; }
        public string Material_Remark { get; set; }
        public string Material_IsNeedCheck { get; set; }
        public Nullable<int> Material_StockLife { get; set; }
        public Nullable<int> Material_CombinQty { get; set; }
        public Nullable<int> Material_UpperQty { get; set; }
        public Nullable<int> Material_LowerQty { get; set; }
        public Nullable<int> Material_Weight_g { get; set; }
        public string Material_Size_LxWxH_cm { get; set; }
    }
}
