//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_OperateLog
    {
        public long ID { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string IPAddress { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string LoginName { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        public virtual B_User B_User { get; set; }
    }
}
