//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL_DETAIL()
        {
            this.INVENTORY_HISTORY = new HashSet<INVENTORY_HISTORY>();
            this.TASK_DETAIL = new HashSet<TASK_DETAIL>();
        }
    
        public int ID { get; set; }
        public int BILL_HEADERID { get; set; }
        public int ITEMID { get; set; }
        public Nullable<int> WMSTASKDETAIL { get; set; }
        public Nullable<int> WMSTASKHEADER { get; set; }
        public int WAREHOUSEID { get; set; }
        public int COMPANYID { get; set; }
        public int TOTALQTY { get; set; }
        public Nullable<int> ASSEMBLYQTY { get; set; }
        public Nullable<int> FINISHQTY { get; set; }
        public int STATUS_CFG { get; set; }
        public string BATCH { get; set; }
        public string LOT { get; set; }
        public Nullable<int> WAVEID { get; set; }
        public string WAVEMSG { get; set; }
        public Nullable<System.DateTime> MANUFACTUREDATE { get; set; }
        public Nullable<System.DateTime> EXPIRATIONDATE { get; set; }
        public Nullable<System.DateTime> AGINGDATE { get; set; }
        public int INVENTORYSTS_CFG { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        public virtual BILL_HEADER BILL_HEADER { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL1 { get; set; }
        public virtual ITEM ITEM { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual WAVE WAVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_HISTORY> INVENTORY_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_DETAIL> TASK_DETAIL { get; set; }
    }
}
