//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ProductBOM
    {
        public int isid { get; set; }
        public int ProductId { get; set; }
        public int MaterialId { get; set; }
        public int Ratio { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastUpdated { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
