//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFIG_DETAIL()
        {
            this.ADJUSTBILL_DETAIL = new HashSet<ADJUSTBILL_DETAIL>();
            this.ADJUSTBILL_DETAIL1 = new HashSet<ADJUSTBILL_DETAIL>();
            this.ADJUSTBILL_HEADER = new HashSet<ADJUSTBILL_HEADER>();
            this.BILL_DETAIL = new HashSet<BILL_DETAIL>();
            this.BILL_DETAIL1 = new HashSet<BILL_DETAIL>();
            this.BILL_HEADER = new HashSet<BILL_HEADER>();
            this.BILL_HEADER1 = new HashSet<BILL_HEADER>();
            this.CHECKBILL_DETAIL = new HashSet<CHECKBILL_DETAIL>();
            this.CHECKBILL_HEADER = new HashSet<CHECKBILL_HEADER>();
            this.EQUIPMENT_ADDRESS = new HashSet<EQUIPMENT_ADDRESS>();
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
            this.INVENTORY_HISTORY = new HashSet<INVENTORY_HISTORY>();
            this.INVENTORY_HISTORY1 = new HashSet<INVENTORY_HISTORY>();
            this.PALLET = new HashSet<PALLET>();
            this.POSITION = new HashSet<POSITION>();
            this.STOCKTAKINGBILL_DETAIL = new HashSet<STOCKTAKINGBILL_DETAIL>();
            this.STOCKTAKINGBILL_HEADER = new HashSet<STOCKTAKINGBILL_HEADER>();
            this.STRATEGY_DETAIL = new HashSet<STRATEGY_DETAIL>();
            this.STRATEGY_HEADER = new HashSet<STRATEGY_HEADER>();
            this.TASK_DETAIL = new HashSet<TASK_DETAIL>();
            this.TASK_HEADER = new HashSet<TASK_HEADER>();
            this.TASK_HEADER1 = new HashSet<TASK_HEADER>();
            this.WARECELL = new HashSet<WARECELL>();
            this.WAVE = new HashSet<WAVE>();
        }
    
        public int ID { get; set; }
        public int CONFIG_HEADERID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool SYSTEMCREATED { get; set; }
        public Nullable<int> ROUTE_HEADERID { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string DEFINE03 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADJUSTBILL_DETAIL> ADJUSTBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADJUSTBILL_DETAIL> ADJUSTBILL_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADJUSTBILL_HEADER> ADJUSTBILL_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_DETAIL> BILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_DETAIL> BILL_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_HEADER> BILL_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_HEADER> BILL_HEADER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKBILL_DETAIL> CHECKBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKBILL_HEADER> CHECKBILL_HEADER { get; set; }
        public virtual CONFIG_HEADER CONFIG_HEADER { get; set; }
        public virtual ROUTE_HEADER ROUTE_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT_ADDRESS> EQUIPMENT_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_HISTORY> INVENTORY_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_HISTORY> INVENTORY_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALLET> PALLET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSITION> POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKTAKINGBILL_DETAIL> STOCKTAKINGBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKTAKINGBILL_HEADER> STOCKTAKINGBILL_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STRATEGY_DETAIL> STRATEGY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STRATEGY_HEADER> STRATEGY_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_DETAIL> TASK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_HEADER> TASK_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_HEADER> TASK_HEADER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WARECELL> WARECELL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAVE> WAVE { get; set; }
    }
}
