//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT_ADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPMENT_ADDRESS()
        {
            this.EQUIPMENT_ALARMTEXT = new HashSet<EQUIPMENT_ALARMTEXT>();
        }
    
        public int ID { get; set; }
        public int EQUIPMENTID { get; set; }
        public string IP { get; set; }
        public string ADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
        public int TYPE_CFG { get; set; }
        public int LENGTH { get; set; }
        public string READVALUES { get; set; }
        public string READQUALITY { get; set; }
        public System.DateTime READSTAMP { get; set; }
        public string WRITEVALUES { get; set; }
        public string WRITESTEMP { get; set; }
        public string WRITEQUALITY { get; set; }
        public Nullable<int> WRITEFLAG { get; set; }
        public Nullable<bool> ENABLE { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string DEFINE03 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT_ALARMTEXT> EQUIPMENT_ALARMTEXT { get; set; }
    }
}
