//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_ITEM
    {
        public int id { get; set; }
        public string code { get; set; }
        public string companyCode { get; set; }
        public string warehouseCode { get; set; }
        public string name { get; set; }
        public string parentCode { get; set; }
        public string packingClass { get; set; }
        public string movementClass { get; set; }
        public string abcClass { get; set; }
        public Nullable<int> daysToExpire { get; set; }
        public string locatingRule { get; set; }
        public string allocationRule { get; set; }
        public string replenishmentRule { get; set; }
        public string emptyLocRule { get; set; }
        public string itemCategory1 { get; set; }
        public string itemCategory2 { get; set; }
        public string itemCategory3 { get; set; }
        public string itemCategory4 { get; set; }
        public string class01 { get; set; }
        public string class02 { get; set; }
        public string class03 { get; set; }
        public string attributeTemplateCode { get; set; }
        public Nullable<int> trackSerialNum { get; set; }
        public Nullable<int> autoGenSerialNum { get; set; }
        public string autoGenSerialNumFormat { get; set; }
        public string snTemplateCode { get; set; }
        public string brand { get; set; }
        public string division { get; set; }
        public string department { get; set; }
        public string itemSize { get; set; }
        public string itemColor { get; set; }
        public string itemStyle { get; set; }
        public Nullable<decimal> costPrice { get; set; }
        public Nullable<decimal> listPrice { get; set; }
        public Nullable<decimal> netPrice { get; set; }
        public string placeOfOrigin { get; set; }
        public string itemAttributeTemplateCode { get; set; }
        public string itemAttribute1 { get; set; }
        public string itemAttribute2 { get; set; }
        public string itemAttribute3 { get; set; }
        public string itemAttribute4 { get; set; }
        public string itemAttribute5 { get; set; }
        public string itemAttribute6 { get; set; }
        public string itemAttribute7 { get; set; }
        public string itemAttribute8 { get; set; }
        public Nullable<int> maintainSts { get; set; }
        public Nullable<int> trackBatch { get; set; }
        public Nullable<int> trackLot { get; set; }
        public Nullable<int> trackManufactureDate { get; set; }
        public Nullable<int> trackExpirationDate { get; set; }
        public Nullable<int> trackAgingDate { get; set; }
        public Nullable<int> expiringDays { get; set; }
        public Nullable<int> minShelfLifeDays { get; set; }
        public Nullable<int> ipQty { get; set; }
        public string unitDesc { get; set; }
        public Nullable<decimal> unitLength { get; set; }
        public Nullable<decimal> unitWidth { get; set; }
        public Nullable<decimal> unitHeight { get; set; }
        public Nullable<decimal> unitWeight { get; set; }
        public Nullable<decimal> unitVolume { get; set; }
        public Nullable<int> eaAsLooseInbound { get; set; }
        public Nullable<int> eaAsLooseOutbound { get; set; }
        public Nullable<int> csQty { get; set; }
        public string csDesc { get; set; }
        public Nullable<decimal> csLength { get; set; }
        public Nullable<decimal> csWidth { get; set; }
        public Nullable<decimal> csHeight { get; set; }
        public Nullable<decimal> csWeight { get; set; }
        public Nullable<decimal> csVolume { get; set; }
        public Nullable<int> csAsLooseInbound { get; set; }
        public Nullable<int> csAsLooseOutbound { get; set; }
        public Nullable<int> plQty { get; set; }
        public string plDesc { get; set; }
        public Nullable<decimal> plLength { get; set; }
        public Nullable<decimal> plWidth { get; set; }
        public Nullable<decimal> plHeight { get; set; }
        public Nullable<decimal> plWeight { get; set; }
        public Nullable<decimal> plVolume { get; set; }
        public string tiHi { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime created { get; set; }
        public string createdBy { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public string lastUpdatedBy { get; set; }
        public Nullable<int> version { get; set; }
        public string userDef1 { get; set; }
        public string userDef2 { get; set; }
        public string userDef3 { get; set; }
        public string userDef4 { get; set; }
        public string userDef5 { get; set; }
        public string userDef6 { get; set; }
        public string userDef7 { get; set; }
        public string userDef8 { get; set; }
        public Nullable<int> iqcType { get; set; }
        public Nullable<decimal> iqcQty { get; set; }
        public Nullable<int> interface_status { get; set; }
        public Nullable<System.DateTime> interface_stamp { get; set; }
    }
}
