//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_BILLSTOCKTAKING
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string countType { get; set; }
        public int status { get; set; }
        public string companyCode { get; set; }
        public string locationCode { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public int systemQty { get; set; }
        public int countQty { get; set; }
        public string inventoryType { get; set; }
        public string remark { get; set; }
        public string define01 { get; set; }
        public string define02 { get; set; }
        public string define03 { get; set; }
        public string define04 { get; set; }
        public string define05 { get; set; }
        public string define06 { get; set; }
    }
}
