//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_BILLIN
    {
        public int ID { get; set; }
        public string warehouseCode { get; set; }
        public string Code { get; set; }
        public string receiptType { get; set; }
        public string shipFromCode { get; set; }
        public string shipFromName { get; set; }
        public string PLN { get; set; }
        public string receiptNote { get; set; }
        public string lineNo { get; set; }
        public string companyCode { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public int totalQty { get; set; }
        public int openQty { get; set; }
        public string inventoryType { get; set; }
        public string unit { get; set; }
        public string batch { get; set; }
        public string lot { get; set; }
        public Nullable<System.DateTime> manufacureDate { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public string inventorySts { get; set; }
        public string kitFlag { get; set; }
        public string remark { get; set; }
        public string define01 { get; set; }
        public string define02 { get; set; }
        public string define03 { get; set; }
        public string define04 { get; set; }
        public string define05 { get; set; }
        public string define06 { get; set; }
    }
}
