//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_BILLOUT
    {
        public int ID { get; set; }
        public string warehouseCode { get; set; }
        public string Code { get; set; }
        public string shipmentType { get; set; }
        public string shipFromCode { get; set; }
        public Nullable<System.DateTime> requestdDeliveryDate { get; set; }
        public string sourcePlatform { get; set; }
        public string carrierCode { get; set; }
        public string carrierService { get; set; }
        public string primaryWaybillCode { get; set; }
        public string shortAddress { get; set; }
        public string storeCode { get; set; }
        public string storeName { get; set; }
        public Nullable<decimal> totalValue { get; set; }
        public int codRequired { get; set; }
        public Nullable<decimal> codValue { get; set; }
        public int invoiceRequired { get; set; }
        public string invoiceHeader { get; set; }
        public Nullable<decimal> invoiceAmount { get; set; }
        public Nullable<decimal> itemPrice { get; set; }
        public Nullable<decimal> itemAmount { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public int planQty { get; set; }
        public string remark { get; set; }
        public string define01 { get; set; }
        public string define02 { get; set; }
        public string define03 { get; set; }
        public string define04 { get; set; }
        public string define05 { get; set; }
        public string define06 { get; set; }
    }
}
