//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_HISTORY
    {
        public int ID { get; set; }
        public int INVENTORYID { get; set; }
        public int PALLETID { get; set; }
        public int WARECELLID { get; set; }
        public int ITEMID { get; set; }
        public int TYPE_CFG { get; set; }
        public decimal QUANTITY { get; set; }
        public Nullable<decimal> LOCKQUANTITY { get; set; }
        public int BILL_DETAILID { get; set; }
        public int TASK_DETAILID { get; set; }
        public int INVENTORYSTS_CFG { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string DEFINE03 { get; set; }
        public string DEFINE04 { get; set; }
        public string DEFINE05 { get; set; }
        public string DEFINE06 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        public virtual BILL_DETAIL BILL_DETAIL { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL1 { get; set; }
        public virtual INVENTORY INVENTORY { get; set; }
        public virtual ITEM ITEM { get; set; }
        public virtual PALLET PALLET { get; set; }
        public virtual TASK_DETAIL TASK_DETAIL { get; set; }
        public virtual WARECELL WARECELL { get; set; }
    }
}
