//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_ZONE_CAPACITY
    {
        public int ID { get; set; }
        public int COMPANYID { get; set; }
        public int ITEMID { get; set; }
        public int ZONEID { get; set; }
        public int MAXQTY { get; set; }
        public int MINQTY { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual ITEM ITEM { get; set; }
        public virtual ZONE ZONE { get; set; }
    }
}
