//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.ADJUSTBILL_DETAIL = new HashSet<ADJUSTBILL_DETAIL>();
            this.BILL_DETAIL = new HashSet<BILL_DETAIL>();
            this.CHECKBILL_DETAIL = new HashSet<CHECKBILL_DETAIL>();
            this.INVENTORY_HISTORY = new HashSet<INVENTORY_HISTORY>();
            this.ITEM_PALLET_CAPACITY = new HashSet<ITEM_PALLET_CAPACITY>();
            this.ITEM_ZONE_CAPACITY = new HashSet<ITEM_ZONE_CAPACITY>();
            this.STOCKTAKINGBILL_DETAIL = new HashSet<STOCKTAKINGBILL_DETAIL>();
            this.TASK_DETAIL = new HashSet<TASK_DETAIL>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public int COMPANYID { get; set; }
        public int WAREHOUSEID { get; set; }
        public string NAME { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> DAYSTOEXPIRE { get; set; }
        public Nullable<int> EXPIRINGDAYS { get; set; }
        public Nullable<int> MINSHELFLIFEDAYS { get; set; }
        public Nullable<int> CSQTY { get; set; }
        public string CSDESC { get; set; }
        public Nullable<decimal> CSLENGTH { get; set; }
        public Nullable<decimal> CSWIDTH { get; set; }
        public Nullable<decimal> CSHEIGHT { get; set; }
        public Nullable<decimal> CSWEIGHT { get; set; }
        public Nullable<decimal> CSVOLUME { get; set; }
        public Nullable<int> PLQTY { get; set; }
        public string PLDESC { get; set; }
        public Nullable<decimal> PLLENGTH { get; set; }
        public Nullable<decimal> PLWIDTH { get; set; }
        public Nullable<decimal> PLHEIGHT { get; set; }
        public Nullable<decimal> PLWEIGHT { get; set; }
        public Nullable<decimal> PLVOLUME { get; set; }
        public string TIHI { get; set; }
        public Nullable<bool> ENABLE { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string USERDEF4 { get; set; }
        public string USERDEF5 { get; set; }
        public string USERDEF6 { get; set; }
        public Nullable<int> IQCTYPE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public Nullable<int> ALLOCATIONRULE_STRATEGY_HEADERID { get; set; }
        public Nullable<int> REPLENISHMENTRULE_STRATEGY_HEADERID { get; set; }
        public Nullable<int> MOVERULE_STRATEGY_HEADERID { get; set; }
        public Nullable<int> RECEIPTRULE_STRATEGY_HEADERID { get; set; }
        public Nullable<int> WARECELLRULE_STRATEGY_HEADERID { get; set; }
        public Nullable<int> ROADWAYRULE_STRATEGY_HEADERID { get; set; }
        public Nullable<int> ZONERULE_STRATEGY_HEADERID { get; set; }
        public string CLASS01 { get; set; }
        public string CLASS02 { get; set; }
        public string CLASS03 { get; set; }
        public string BRAND { get; set; }
        public string ITEMSIZE { get; set; }
        public string ITEMCOLOR { get; set; }
        public string ITEMSTYLE { get; set; }
        public string PLACEOFORIGIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADJUSTBILL_DETAIL> ADJUSTBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_DETAIL> BILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKBILL_DETAIL> CHECKBILL_DETAIL { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_HISTORY> INVENTORY_HISTORY { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER1 { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER2 { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER3 { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER4 { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER5 { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER6 { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_PALLET_CAPACITY> ITEM_PALLET_CAPACITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_ZONE_CAPACITY> ITEM_ZONE_CAPACITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKTAKINGBILL_DETAIL> STOCKTAKINGBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_DETAIL> TASK_DETAIL { get; set; }
    }
}
