//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_OPERATOR
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public string CLIENTNAME { get; set; }
        public string LOGINER { get; set; }
        public int TYPE_CFG { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> STAMP { get; set; }
    }
}
