//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POSITION()
        {
            this.EQUIPMENT_ALARMRECORD = new HashSet<EQUIPMENT_ALARMRECORD>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string NAME2 { get; set; }
        public Nullable<int> POSITIONX { get; set; }
        public Nullable<int> POSITIONY { get; set; }
        public Nullable<int> POSITIONZ { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> ZONEID { get; set; }
        public Nullable<int> EQUIPMENTID { get; set; }
        public Nullable<int> PORTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> STATUSSTAMP { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string DEFINE03 { get; set; }
        public string DEFINE04 { get; set; }
        public string DEFINE05 { get; set; }
        public string DEFINE06 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public Nullable<int> CONFIG_DETAIL_ID { get; set; }
    
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT_ALARMRECORD> EQUIPMENT_ALARMRECORD { get; set; }
        public virtual PORT PORT { get; set; }
        public virtual ZONE ZONE { get; set; }
    }
}
