//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIAL_NUMBER
    {
        public int ID { get; set; }
        public string PRIMARYFIELD { get; set; }
        public string PREFIX { get; set; }
        public string SUFFIX { get; set; }
        public string PADDINGCHAR { get; set; }
        public string PADDINGPOS { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public string MINID { get; set; }
        public string MAXID { get; set; }
        public Nullable<int> CURRENTVALUES { get; set; }
        public Nullable<int> ISSERIAL { get; set; }
        public string RESTBYDAY { get; set; }
        public string RESTBYWEEK { get; set; }
        public string RESTBYMONTH { get; set; }
        public string RESTBYYEAR { get; set; }
        public string YYMMDD { get; set; }
        public Nullable<System.DateTime> MODIFITIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    }
}
