//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class STACKER
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public string WORKMODEL { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CURRENTLOCATION { get; set; }
        public Nullable<int> STACKER1TASKNO { get; set; }
        public string STACKER1WORKTYPE { get; set; }
        public string STACKER1SOURCE { get; set; }
        public string STACKER1DESTINATION { get; set; }
        public string STACKER1ERROR { get; set; }
        public Nullable<int> STACKER2TASKNO { get; set; }
        public string STACKER2WORKTYPE { get; set; }
        public string STACKER2SOURCE { get; set; }
        public string STACKER2DESTINATION { get; set; }
        public string STACKER2ERROR { get; set; }
        public Nullable<bool> CONNECTSTATE { get; set; }
        public int ROADWAYID { get; set; }
        public bool ACTIVE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        public virtual ROADWAY ROADWAY { get; set; }
    }
}
