//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKTAKINGBILL_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCKTAKINGBILL_HEADER()
        {
            this.ADJUSTBILL_HEADER = new HashSet<ADJUSTBILL_HEADER>();
            this.STOCKTAKINGBILL_DETAIL = new HashSet<STOCKTAKINGBILL_DETAIL>();
        }
    
        public int ID { get; set; }
        public string BILLNO { get; set; }
        public Nullable<int> WAREHOUSEID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> ZONEID { get; set; }
        public string BATCH { get; set; }
        public int STATUS_CFG { get; set; }
        public Nullable<int> STRATEGY_HEADERID { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public bool ISTASKHEADER { get; set; }
        public bool ISADJUSTBILL { get; set; }
        public bool ENABLE { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string DEFINE03 { get; set; }
        public string DEFINE04 { get; set; }
        public string DEFINE05 { get; set; }
        public string DEFINE06 { get; set; }
        public string DEFINE07 { get; set; }
        public string DEFINE08 { get; set; }
        public string VERIFYBY { get; set; }
        public Nullable<System.DateTime> VERIFYTIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADJUSTBILL_HEADER> ADJUSTBILL_HEADER { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKTAKINGBILL_DETAIL> STOCKTAKINGBILL_DETAIL { get; set; }
        public virtual STRATEGY_HEADER STRATEGY_HEADER { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual ZONE ZONE { get; set; }
    }
}
