//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK_HEADER()
        {
            this.TASK_DETAIL = new HashSet<TASK_DETAIL>();
        }
    
        public int ID { get; set; }
        public int OPCTASKNO { get; set; }
        public int PALLETID { get; set; }
        public Nullable<int> R_PORTID { get; set; }
        public Nullable<int> S_PORTID { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public Nullable<int> ROADWAYID { get; set; }
        public Nullable<int> S_WARECELLID { get; set; }
        public Nullable<int> D_WARECELLID { get; set; }
        public int STATUS_CFG { get; set; }
        public int TYPE_CFG { get; set; }
        public int PRIORITY { get; set; }
        public string STARTBY { get; set; }
        public Nullable<System.DateTime> STARTETIME { get; set; }
        public string FINISHBY { get; set; }
        public Nullable<System.DateTime> FINISHETIME { get; set; }
        public Nullable<int> WAVEID { get; set; }
        public string WAVEMSG { get; set; }
        public Nullable<int> ACCOUNTTYPE { get; set; }
        public string DEFINE01 { get; set; }
        public string DEFINE02 { get; set; }
        public string DEFINE03 { get; set; }
        public string DEFINE04 { get; set; }
        public string DEFINE05 { get; set; }
        public string DEFINE06 { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public Nullable<int> WARECELL_ID { get; set; }
        public Nullable<int> WARECELL_ID1 { get; set; }
        public Nullable<int> PORT_ID { get; set; }
        public Nullable<int> PORT_ID1 { get; set; }
    
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL1 { get; set; }
        public virtual PALLET PALLET { get; set; }
        public virtual PORT PORT { get; set; }
        public virtual PORT PORT1 { get; set; }
        public virtual ROADWAY ROADWAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_DETAIL> TASK_DETAIL { get; set; }
        public virtual WARECELL WARECELL { get; set; }
        public virtual WARECELL WARECELL1 { get; set; }
        public virtual WAVE WAVE { get; set; }
    }
}
