//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMES.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAVE()
        {
            this.BILL_DETAIL = new HashSet<BILL_DETAIL>();
            this.TASK_HEADER = new HashSet<TASK_HEADER>();
        }
    
        public int ID { get; set; }
        public int WAVE_HEADERID { get; set; }
        public int STATUS_CFG { get; set; }
        public Nullable<int> TOTALSHIPMENTS { get; set; }
        public Nullable<int> TOTALLINES { get; set; }
        public Nullable<int> TOTALQTY { get; set; }
        public string ERRORMESSAGE { get; set; }
        public string RUNBY { get; set; }
        public Nullable<System.DateTime> RUNSTMP { get; set; }
        public string RELEASEDBY { get; set; }
        public Nullable<System.DateTime> RELEASEDSTAMP { get; set; }
        public string PROCESSSTAMP { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public string CLOSEDBY { get; set; }
        public Nullable<System.DateTime> CLOSEDSTAMP { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<bool> ISDELETED { get; set; }
        public int C_WAVE_DETAILID { get; set; }
        public int L_WAVE_DETAILID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_DETAIL> BILL_DETAIL { get; set; }
        public virtual CONFIG_DETAIL CONFIG_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_HEADER> TASK_HEADER { get; set; }
        public virtual WAVE_HEADER WAVE_HEADER { get; set; }
        public virtual WAVE_DETAIL WAVE_DETAIL { get; set; }
        public virtual WAVE_DETAIL WAVE_DETAIL1 { get; set; }
    }
}
